spring.datasource.url=jdbc:postgresql://localhost:5432/tasklist
spring.datasource.username=postgres
spring.datasource.password=ruzgar99

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect